DEFMIME(".*\\.(s|)htm(|l)",	"text/html")
DEFMIME(".*\\.css",		"text/css")
DEFMIME(".*\\.xml",		"text/xml")
DEFMIME(".*\\.js",		"text/javascript")
DEFMIME(".*\\.atom",		"application/atom+xml")
DEFMIME(".*\\.rss",		"application/rss+xml")

DEFMIME(".*\\.(txt|log|lst|c((|o)nf|fg)|pc|am|in|(|k)sh|diff|patch|s|((c|h)(|c|h|pp|xx|s))|m4|asm|java|cmake|vim|def|f(77|90))",	"text/plain")
DEFMIME(".*/(README|INSTALL|AUTHORS|COPY(ING|RIGHT)|TODO|ChangeLog|NOTES|NEWS|config(|ure)|Makefile|libtool|missing|depcomp|install-sh)(|\\..*)",	"text/plain")
DEFMIME(".*\\.p(l|m)",		"text/x-script.perl")
DEFMIME(".*\\.py",		"text/x-script.python")
DEFMIME(".*\\.py(c|o)",		"application/x-bytecode.python")
DEFMIME(".*\\.t(cl|k)",		"text/x-tcl")
DEFMIME(".*\\.p(hp|html)(|s|[0-9]{,2})",	"text/x-php")
DEFMIME(".*\\.asp(|x))",	"text/asp")
DEFMIME(".*\\.(pas|dpr)",	"text/pascal")

DEFMIME(".*\\.gif",		"image/gif")
DEFMIME(".*\\.jp(|e)g",		"image/jpeg")
DEFMIME(".*\\.png",		"image/png")
DEFMIME(".*\\.tif(|f)",		"image/tiff")
DEFMIME(".*\\.ico",		"image/x-icon")
DEFMIME(".*\\.xcf",		"image/x-xcf")
DEFMIME(".*\\.xbm",		"image/x-xbitmap")
DEFMIME(".*\\.xpm",		"image/x-xpmi")
DEFMIME(".*\\.bmp",		"image/x-ms-bmp")
DEFMIME(".*\\.svg(|z)",		"image/svg+xml")
DEFMIME(".*\\.webp",		"image/webp")
DEFMIME(".*\\.dwg",		"image/vnd.dwg")

DEFMIME(".*\\.(|t)gz(|ip)",	"application/x-gzip")
DEFMIME(".*\\.(|t)bz(|2)",	"application/x-bzip2")
DEFMIME(".*\\.(|t)xz",		"application/x-xz")
DEFMIME(".*\\.z",		"application/x-compressed")
DEFMIME(".*\\.tar",		"application/x-tar")
DEFMIME(".*\\.7z",		"application/x-7z-compressed")
DEFMIME(".*\\.7z",		"application/x-7z-compressed")
DEFMIME(".*\\.zip",		"application/zip")
DEFMIME(".*\\.r(ar|[0-9]{,2})",	"application/x-rar-compressed")
DEFMIME(".*\\.(j|w|e)ar",	"application/java-archive")
DEFMIME(".*\\.run",		"application/x-makeself")
DEFMIME(".*\\.rpm",		"application/x-redhat-package-manager")

DEFMIME(".*\\.doc(|x)",		"application/msword")
DEFMIME(".*\\.xls(|x)",		"application/vnd.ms-excel")
DEFMIME(".*\\.ppt(|x)",		"application/vnd.ms-powerpoint")
DEFMIME(".*\\.pdf",		"application/pdf")
DEFMIME(".*\\.((|e)ps|ai)",	"application/postscript")
DEFMIME(".*\\.rtf",		"application/rtf")
DEFMIME(".*\\.swf",		"application/x-shockwave-flash")
DEFMIME(".*\\.(der|pem|crt)",	"application/x-x509-ca-cert")
DEFMIME(".*\\.xpi",		"application/x-xpinstall")
DEFMIME(".*\\.xhtml",		"application/xhtml+xml")

DEFMIME(".*\\.m3u",		"audio/x-mpequrl")

DEFMIME(".*\\.mp3",		"audio/mpeg")
DEFMIME(".*\\.ogg",		"audio/ogg")
DEFMIME(".*\\.m4a",		"audio/x-m4a")
DEFMIME(".*\\.au",		"audio/x-au")
DEFMIME(".*\\.(mid(|i))",	"audio/midi")
DEFMIME(".*\\.mod",		"audio/mod")
DEFMIME(".*\\.xm",		"audio/xm")
DEFMIME(".*\\.it",		"audio/it")
DEFMIME(".*\\.s3m",		"audio/s3m")

DEFMIME(".*\\.mp4",		"video/mp4")
DEFMIME(".*\\.avi",		"video/x-msvideo")
DEFMIME(".*\\.flv",		"video/x-flv")
DEFMIME(".*\\.mov",		"video/quicktime")
DEFMIME(".*\\.wmv",		"video/x-ms-wmv")
DEFMIME(".*\\.3gp(|p)",		"video/3gpp")
DEFMIME(".*\\.mp(|e)g",		"video/mpeg")
DEFMIME(".*\\.webm",		"video/webm")
DEFMIME(".*\\.m4v",		"video/x-m4v")
DEFMIME(".*\\.mng",		"video/x-mng")
